name: foodbar
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  mobile_scanner: ^6.0.2
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.2"

flutter:
  uses-material-design: true
  assets:
    - "assets/"

flutter_native_splash:
  color: "#50C878"
  image: "assets/logo.png"

  android_12:
    image: "assets/logo.png"
    color: #50C878

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"
